[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1IzvwmlYYt-exsXAMYZQXywGjRe3Cpi0swaR_OK5iZRc/edit?gid=0#gid=0"

[connections.gsheets.service_account_info]
type = "service_account"
project_id = "ncaa-draft-2026-490502"
private_key_id = "3b9bc27874ef9410fc45f064b94c485c043420f4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDgkgp0Xffq3P/m
peYabrnuqn9Aei2vBNvEYDFXt25qAwlR3W4YZai6l1LMIqYPq7tdXRGcTzvhUCXz
9nf8X5u20pb+rJ//mQx8wAYuvli/20T4aWkilvv4HiFFbmvEl6p4j3PnbMsUoihp
ItqfAjMgmRP2YkzUV2BatSPX/L5jUtMtVSj4LBoCNWXmxiO1OFbTNptYfhBgzGaF
CILc0DbClc7JHf3yEA3y6f9RawGzOTwtvtVQD8wQaz+WgwZFMceCT4z894CPwiF8
UH08Wto2rIQiAKzzpxc4aeh0bXtRR/BGUsVCR0xOE6ZTr8jSKBs2hAId8BsO+Wdf
FwMtpk1xAgMBAAECggEAD/LHK8r1nZga01hCTmvBKB4zIdLbdjO/4MMdFfforz4u
dgIl/LURhcjT4Dvws6m0SXXf14w3+jEdNOVy0Xk/v3zWrNj5FueZX62qcrzhZCSw
Ef04cnSrCcyn+7yTCjfkKyIy7sNG69z1RjwrrwGyvFSquoNyJd1bsi1tkXv5UGfS
B4qOXg3yE0X5FEkBPMAF8JPqq8TB2TMN4l26hZmp3ZC/Wwq4CfEOdyofTOgCm7AZ
oCfj5ilgrWUP/y8oVCLrFndFDemtlycuQvs5q59hSm2OgkNdeCHSKwkr/n7xGgeX
iwv5FgTX8iBUgQEZGjSaeazJAr2bG2q9ykpI71M5vQKBgQD/uTbw78FIyNkLMSlq
o9SOwLrhk0ZYMaiZu4UzFGw+8iHIGdS5V7VCpuI5S7U+tMYdPGNKRqXBD/H8fxuc
cdqGhLuFDtfT1N6d8RxdOeeCG8Z9pSlOXax2FwnV0aBjse3dCTSMN9sWUva/6Tm2
/7aBFAyVG3+ZeInFGevEDJfAbQKBgQDg0DPzRb4gbkkD1LnOBiQXPoH7fUbr50+F
62cS0iEyF3Teh635lUZ9PCEo2SdiZZxszMeGlCGuVV9D4Bpr6cvSSePB5pNRw3fV
4AUMJd66wCo4KmzsyKYWFuRlUxA3+tbqUn/xZiwiPH8yqOl9E27M+9p9mvw5M6h7
eiymixvGlQKBgQDW+6ast2MPBYsyVYo0FLdFq9FwgpfI3TaYx4UbhDfcU0MDLnQf
vRStjA7zjCo7JU7IlVQDxZDj1bviQhm8VBsaq8vZ+LiJZZQhw+nMljmCsEcWqhsn
vqiWPpgOIcVtCtCl2m9K0kplYin+/NuAdUnBClHpqMyFAUkRYtFKaCvLoQKBgQC5
eIujhEJbFyF9255+7moQEy3BgZVlQixFW/RpfpqMbPWqMV3Crvi8kUL6JE1tzE7F
JBzoVoWDAkPaB6VEqlnRX8xbSBL6Pb074dnIL+YVRDyQoc/DebYsOy6quWCEDpoI
L5AGZDi89hQqg1g+LC4ZRx72yUqVFp1FYYI81D9SEQKBgCjz+/JkU+vle+Id6Ept
tWyp1M45emBoepxaM6WOmQqPxTzPU2h0MmKGYBXXpS79VEReWsuxGiUD1JTpPuVI
gy/dO7pxSIOrZdHQRD4rUCqCT5ZPAvgaW9ymIhT/QADP6kcSsYdmZS1QdejdORTb
wYY+hYNucQaLMXKm0BJAbSwc
-----END PRIVATE KEY-----
"""
client_email = "streamlit-draft-bot@ncaa-draft-2026-490502.iam.gserviceaccount.com"
client_id = "112667138122694343179"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-draft-bot%40ncaa-draft-2026-490502.iam.gserviceaccount.com"
universe_domain = "googleapis.com"